name: Publish package

on: [push]
  #workflow_run:
  #  workflows: ["Create Release"]
  #  types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      ##########################################
      #   1 - PUSH TO MAVEN CENTRAL
      ##########################################
      ##########################################
      #   2 - PUSH TO GITHUB PACKAGE
      ##########################################
      # STEP 1: Set up Java for publishing to Maven Central Repository
      - name: Set up Java for publishing to GitHub Package
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          server-username: github
          server-password: ${{ secrets.GITHUB_TOKEN }}
      # STEP 2: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -Dmaven.test.skip=true -P "github"
